nzbget:
  image: linuxserver/nzbget
  restart: always
  environment:
    - PUID=0
    - PGID=0
  ports:
    - "6789:6789"
  volumes:
    - "/mnt/aufs:/downloads"
    - "/data/warehouse/nzbget:/config"

sonarr:
  image: linuxserver/sonarr
  restart: always
  environment:
    - PUID=0
    - PGID=0
  ports:
    - "8989:8989"
  volumes:
    - "/dev/rtc:/dev/rtc:ro"
    - "/data/warehouse/sonarr:/config"
    - "/mnt/aufs/TV:/tv"
    - "/data/warehouse/nzbget/downloads/incoming:/downloads/incoming"

couchpotato:
  build: couchpotato
  restart: always
  ports:
    - "5050:5050"
  volumes:
    - "/data/warehouse/couchpotato:/data"
    - "/mnt/aufs:/mnt/media"

