nzbget:
  image: linuxserver/nzbget
  restart: always
  environment:
    - PUID=0
    - PGID=0
  ports:
    - "6789:6789"
  volumes:
    - "/mnt/aufs/MOVIES - HD:/downloads/Movies"
    - "/data/warehouse/nzbget:/config"
    - "/data/warehouse/nzbget/downloads/incoming:/downloads/incoming"
sonarr:
  image: linuxserver/sonarr
  restart: always
  environment:
    - PUID=0
    - PGID=0
  ports:
    - "8989:8989"
  volumes:
    - "/dev/rtc:/dev/rtc:ro"
    - "/data/warehouse/sonarr:/config"
    - "/mnt/aufs/TV:/tv"
    - "/data/warehouse/nzbget/downloads/incoming:/downloads/incoming"
tautulli:
  image: linuxserver/tautulli
  restart: always
  environment:
    - PUID=0
    - PGID=0
    - TZ=America/Kentucky/Louisville
  ports:
    - "8181:8181"
  volumes:
    - "/data/warehouse/tautulli:/config"
    - "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs:/logs:ro"
    - "/dev/rtc:/dev/rtc:ro"
radarr:
  image: linuxserver/radarr
  restart: always
  environment:
    - PUID=0
    - PGID=0
  ports:
    - "7878:7878"
  volumes:
    - "/data/warehouse/radarr:/config"
    - "/data/warehouse/nzbget/downloads/incoming:/downloads/incoming"
    - "/mnt/aufs/MOVIES - HD:/movies"
    - "/dev/rtc:/dev/rtc:ro"
